### PR TITLE
Updated k8s registry from k8s.gcr.io to registry.k8s.io

### PR DESCRIPTION
**Pull request by RishabhKodes**
**What this PR does / why we need it**:
This PR is part of the Umbrella issue, https://github.com/kubernetes/k8s.io/issues/4780

**Special notes for your reviewer**:
With the change to defaulting to registry.k8s.io as the image registry and the planned freeze in April, 
downstream projects will likely be impacted, so the image registry needs 
to be updated from k8s.gcr.io to registry.k8s.io.

### CODE REVIEW

**Comment by RishabhKodes** [comment]
@xpivarc mentioned about this issue here, https://github.com/kubevirt/kubevirt/pull/9262#issuecomment-1443710928

**Comment by xpivarc** [comment]
/lgtm
@AlonaKaplan

**Comment by AlonaKaplan** [comment]
@RishabhKodes Thanks for the PR! The github action should be updated as well - https://github.com/kubevirt/kubesecondarydns/blob/main/.github/workflows/image-push.yaml#L56

**Comment by RishabhKodes** [comment]
> @RishabhKodes Thanks for the PR! The github action should be updated as well - https://github.com/kubevirt/kubesecondarydns/blob/main/.github/workflows/image-push.yaml#L56

@AlonaKaplan not quite sure, what should be updated here?

**Comment by AlonaKaplan** [comment]
> > @RishabhKodes Thanks for the PR! The github action should be updated as well - https://github.com/kubevirt/kubesecondarydns/blob/main/.github/workflows/image-push.yaml#L56
> 
> @AlonaKaplan not quite sure, what should be updated here?

Sorry, ignore my comment. I confused `ghcr.io` with `k8s.gcr.io`.

/approve
/hold
@oshoval please review the PR, feel free to remove the hold.

**Comment by oshoval** [comment]
Thank you for the contribution

/lgtm
/hold cancel

**Comment by oshoval** [comment]
it is weird that it didnt run the gitactions

**Comment by oshoval** [comment]
@AlonaKaplan can you please issue a tag ? (manual bump is needed as well on CNAO afterwards)
we better bump CNAO to be aware of it, so in case the old domain doesn't work, it wont be broken on CNAO / HCO
Thanks

**Pull request merged**
