### PR TITLE
feat: add snyk file to exclude vendor folders

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
This file is used for snyk integration to config snyk scan.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by phoracek** [comment]
@oshoval would we still get an alert if our dependencies contain CVEs?

**Comment by oshoval** [comment]
> @oshoval would we still get an alert if our dependencies contain CVEs?

Yes, this is for excluding the vendor folder during Code analysis
Packages analyzing is done via go.mod, not via Code analysis

**Comment by phoracek** [comment]
Understood. Thanks!

**Pull request merged**
