### PR TITLE
Remove release-note from the PR template

### PR DESCRIPTION
**Pull request by AlonaKaplan**
**What this PR does / why we need it**:
The repository has a github action that generates the changelog of the release with the PR title.
It should be enough.

**Special notes for your reviewer**:
The PR depends on https://github.com/kubevirt/project-infra/pull/2548

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
Closing temporary till the project-infra is merged.

**Comment by oshoval** [comment]
This template just ask the user to add the release notes
nothing beside

Project infra already has the plugin
Just the github actions was missing

**Comment by AlonaKaplan** [comment]
> This template just ask the user to add the release notes nothing beside
> 
> Project infra already has the plugin Just the github actions was / is missing

As the PR description says, the release github [action](https://github.com/kubevirt/kubesecondarydns/blob/main/.github/workflows/image-push.yaml#L69) already generate a releasen-note with out the need to manually add the text to each PR.
It is more than enough.

I couldn't find a github action that collects the release-note from each PR and adds all those notes to the change-log.
[cnao](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/hack/render-release-notes.sh#L14) for example are using k8s.io/release/cmd/release-notes binary to gather the notes from the PRs and generate the change log. We can use it as well and append it to our change log, but I find it redundant. The changelog generated by the github action is good enough.

**Comment by oshoval** [comment]
> > This template just ask the user to add the release notes nothing beside
> > Project infra already has the plugin Just the github actions was / is missing
> 
> As the PR description says, the release github [action](https://github.com/kubevirt/kubesecondarydns/blob/main/.github/workflows/image-push.yaml#L69) already generate a releasen-note with out the need to manually add the text to each PR. It is more than enough.
> 
> I couldn't find a github action that collects the release-note from each PR and adds all those notes to the change-log. [cnao](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/hack/render-release-notes.sh#L14) for example are using k8s.io/release/cmd/release-notes binary to gather the notes from the PRs and generate the change log. We can use it as well and append it to our change log, but I find it redundant. The changelog generated by the github action is good enough.

It collects the PR desc,
original plan was indeed to add as CNAO does
It might be less informative on special cases, but we can live without it for now.

**Comment by AlonaKaplan** [comment]
> > > This template just ask the user to add the release notes nothing beside
> > > Project infra already has the plugin Just the github actions was / is missing
> > 
> > 
> > As the PR description says, the release github [action](https://github.com/kubevirt/kubesecondarydns/blob/main/.github/workflows/image-push.yaml#L69) already generate a releasen-note with out the need to manually add the text to each PR. It is more than enough.
> > I couldn't find a github action that collects the release-note from each PR and adds all those notes to the change-log. [cnao](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/hack/render-release-notes.sh#L14) for example are using k8s.io/release/cmd/release-notes binary to gather the notes from the PRs and generate the change log. We can use it as well and append it to our change log, but I find it redundant. The changelog generated by the github action is good enough.
> 
> It collects the PR desc, original plan was indeed to add as CNAO does It might be less informative on special cases, but we can live without it for now.

I discussed it will @qinqon and even in cnao they plan to stop using this binary. The changelog generated by the current github action is more than enough to this repo.

**Review by oshoval — APPROVED** [review]
No need to wait for the infra, as it wont break nothing
Thanks

**Pull request merged**
